### ISSUE TITLE
Datos fijos en el contacto

### ISSUE THREAD

**Issue by sebastian-code** [odoo-colombia/odoo-colombia#23]
En Colombia, parte de la información requerida por la DIAN son los códigos de identificación del DANE para las ciudades, y aunque existe el cuadro de dialogo para hacerlo posible, la instalación de esa modificación hace fija la creación de un contacto como únicamente Colombiano, cuando es posible que clientes y contactos sean del exterior.

**Comment by blaggacao** [comment]
@sebastian-code Vamos a revisar, pero creo que se ha tenido en cuenta para la actualisacion que estamos planenando para la 10 (ver comentario #24). Mil Gracias!
