### ISSUE TITLE
Informacion adicional

### ISSUE THREAD

**Issue by sebastian-code** [odoo-colombia/odoo-colombia#24]
En la plantilla de creación de contactos, se solicita la información de identificación del geográfica del DANE, pero esta casilla no es obligatoria de llenar (cuando es un elemento necesario para la declaración de impuestos en Colombia), y los datos deberán insertarse manualmente, cuando eso podría incluirse previamente, tomando la información del DANE para tal fin.

**Comment by blaggacao** [comment]
@sebastian-code Este repositorio ne se esta manteniendo, es probable que vamos por parte de DevCO Colombia lanzar una actualisacion para la localisacion oficial para la version 10 al igual que poner a disposicion unos modulos de precargamiento de datos. Cordial Saludo
